revision
GeoScripting-WUR/RPythonBasics pull request #1
Opened 2023-07-26 14:12 UTC by Timmarh

Very nice. I added some small suggestions and some spelling things.

2023-07-26 14:20 UTC, GreatEmerald requested changes
Thanks! A few minor corrections.

2023-07-26 14:20 UTC, GreatEmerald commented on index.Rmd
> +Both the `R` and the `python` interpreters can be run from Bash. Here is an example of code that is correct in both python and R. You can use this example to execute a script written in either langua
`Python` should be uppercase here.

2023-07-26 14:20 UTC, GreatEmerald commented on index.Rmd
> +You can combine strings to produce longer strings. This is done with the function `paste()` in R and using the `+` operator in Python (as long as all parts are strings).
This is not very useful :)

2023-07-26 14:20 UTC, GreatEmerald commented on index.Rmd
> +This allows you to run script files even without having any graphical user interface installed or running, which is the fastest way to run any script from top to bottom. You can use this method to tr
No, the original spelling "favourite" is correct, make sure to use the British English spell checker ;)

2023-07-26 14:20 UTC, GreatEmerald commented on index.Rmd
> +    # all text inside curly brackets will be executed as plain python.
Also uppercase Python here

2023-07-26 14:20 UTC, GreatEmerald commented on index.Rmd
> +Note that R also has a more formalized type of classes, called S4 classes, that behave a bit more similar to the Python classes, but S4 classes are generally not recommended to use as they are furthe
Same here, "formalised" is correct British English.

2023-07-27 07:26 UTC, Timmarh commented
Requested changes are changed. Merge?

2023-07-27 09:04 UTC, GreatEmerald approved these changes
Thanks!

2023-07-27 09:04 UTC, merged